BlogPost/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_post.urls', namespace='slug')),
]

blog_post/urls.py
from django.conf.urls import re_path
from .views import (
    PostList,
    DetailPost,
)

app_name = 'blog_post'


urlpatterns = [
    re_path(r'^$', PostList.as_view(), name='home'),
    re_path(r'^(?P<pk>\d+)-(?P<slug>[-\w]+)/$', DetailPost.as_view(), name='post_detail'),
]

blog_post/models.py
from django.db import models


class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)


class BlogPost(models.Model):
    title = models.CharField(max_length=300, blank=False)
    content = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    publish = models.BooleanField(default=True)
    slug = models.SlugField(max_length=200, unique=True)
    objects = EntryQuerySet.as_manager()


    def __str__(self):
        return self.title

blog_post/views.py
from django.views.generic import ListView, DetailView
from .models import BlogPost


class PostList(ListView):
    model = BlogPost
    template_name = 'blog_post/post_list.html'



class DetailPost(DetailView):
    model = BlogPost
    template_name = 'blog_post/post_detail.html'

blog_post/templates/blog_post/post_detail.html
{% extends 'base_home.html' %}
{% block title %}
    <title>Post Details</title>
{% endblock %}


{% block content %}


<div>
    <p><h2>{{ object.title }}</h2></p>
    <p>{{ object.post_date }}</p>
    <p>{{ object.content }}</p>
</div><br>


{% endblock %}

blog_post/templates/blog_post/post_list.html
{% extends 'base_home.html' %}
{% block title %}
    <title>Home</title>
{% endblock %}

{% block content %}

    {% for object in object_list %}
    <div>
        <p><h2><a href="{% url 'blog_post:post_detail' object.pk object.slug %}">{{ object.title }}</a> </h2></p>
        <p>{{ object.post_date }}</p>
    </div><br>
    {% endfor %}

{% endblock %}

templates/base_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}

    {% endblock %}
    <meta charset="UTF-8">
</head>
<body>

<header>
    <div class="topnav">
      <a class="active" href="{% url 'blog_post:home' %}">Home</a>
    </div>
</header>

{% block content %}

{% endblock %}

</body>
</html>